import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Building2, Pencil, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import { queryClient } from "@/lib/queryClient";
import { superAdminApi, type Tenant } from "@/lib/super-admin-api";
import { PageHeader } from "./_shared";

function TenantDialog({ tenant, onClose }: { tenant?: Tenant; onClose: () => void }) {
 const [name,setName]=useState(tenant?.name||""); const [slug,setSlug]=useState(tenant?.slug||""); const [adminName,setAdminName]=useState(""); const [adminEmail,setAdminEmail]=useState(""); const [adminPasswort,setAdminPasswort]=useState(""); const [error,setError]=useState("");
 const mutation=useMutation({mutationFn:()=>tenant?superAdminApi.updateTenant(tenant.id,{name,slug}):superAdminApi.createTenant({name,slug,adminName,adminEmail,adminPasswort}),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["super-admin","tenants"]});queryClient.invalidateQueries({queryKey:["super-admin","overview"]});onClose()},onError:(e:any)=>setError(e.message||"Speichern nicht möglich.")});
 return <Dialog open onOpenChange={onClose}><DialogContent className="max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>{tenant?"Firma bearbeiten":"Neue Firma anlegen"}</DialogTitle></DialogHeader><form className="space-y-4" onSubmit={e=>{e.preventDefault();setError("");mutation.mutate()}}><div className="space-y-1.5"><Label htmlFor="tenant-name">Firmenname</Label><Input id="tenant-name" value={name} onChange={e=>setName(e.target.value)} required /></div><div className="space-y-1.5"><Label htmlFor="tenant-slug">URL-Slug</Label><Input id="tenant-slug" value={slug} onChange={e=>setSlug(e.target.value)} placeholder="muster-sanitaer" required /><p className="text-xs text-muted-foreground">Kleinbuchstaben, Ziffern und Bindestriche; wird bei Bedarf normalisiert.</p></div>{!tenant&&<fieldset className="space-y-4 border-t pt-4"><legend className="text-sm font-medium">Erster Administrator</legend><div className="space-y-1.5"><Label htmlFor="tenant-admin-name">Name</Label><Input id="tenant-admin-name" value={adminName} onChange={e=>setAdminName(e.target.value)} required /></div><div className="space-y-1.5"><Label htmlFor="tenant-admin-email">E-Mail</Label><Input id="tenant-admin-email" type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)} required /></div><div className="space-y-1.5"><Label htmlFor="tenant-admin-password">Temporäres Passwort</Label><Input id="tenant-admin-password" type="password" value={adminPasswort} onChange={e=>setAdminPasswort(e.target.value)} required /></div></fieldset>}{error&&<p className="text-sm text-destructive" role="alert">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={onClose}>Abbrechen</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending?"Wird gespeichert…":"Speichern"}</Button></div></form></DialogContent></Dialog>;
}
export default function FirmenVerwaltung(){const [dialog,setDialog]=useState<Tenant|undefined|false>(false);const {data:tenants=[],isLoading}=useQuery({queryKey:["super-admin","tenants"],queryFn:superAdminApi.tenants});const status=useMutation({mutationFn:({id,active}:{id:string;active:boolean})=>superAdminApi.setTenantStatus(id,active),onSuccess:()=>{queryClient.invalidateQueries({queryKey:["super-admin","tenants"]});queryClient.invalidateQueries({queryKey:["super-admin","overview"]})}});return <div className="space-y-6"><PageHeader title="Firmen" description="Mandanten anlegen, umbenennen sowie aktivieren oder deaktivieren."><Button onClick={()=>setDialog(undefined)} data-testid="button-create-tenant"><Plus className="h-4 w-4"/>Neue Firma anlegen</Button></PageHeader><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/40 text-left text-xs text-muted-foreground"><tr><th className="px-5 py-3">Firma</th><th className="px-5 py-3">Slug</th><th className="px-5 py-3">Mitarbeiter</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Aktionen</th></tr></thead><tbody>{isLoading?<tr><td colSpan={5} className="px-5 py-10 text-center text-muted-foreground">Wird geladen…</td></tr>:tenants.map(t=><tr className="border-t" key={t.id}><td className="px-5 py-3 font-medium"><Building2 className="mr-2 inline h-4 w-4 text-primary"/>{t.name}</td><td className="px-5 py-3 font-mono text-xs text-muted-foreground">{t.slug}</td><td className="px-5 py-3">{t.aktiveMitarbeiter}/{t.mitarbeiterAnzahl}</td><td className="px-5 py-3"><Badge variant={t.status==="aktiv"?"default":"secondary"}>{t.status}</Badge></td><td className="px-5 py-3 text-right"><Button size="sm" variant="ghost" onClick={()=>setDialog(t)} aria-label={`${t.name} bearbeiten`}><Pencil className="h-4 w-4"/>Bearbeiten</Button><Button size="sm" variant="outline" className="ml-2" disabled={status.isPending} onClick={()=>status.mutate({id:t.id,active:t.status!=="aktiv"})}>{t.status==="aktiv"?"Deaktivieren":"Aktivieren"}</Button></td></tr>)}</tbody></table></div></Card>{dialog!==false&&<TenantDialog tenant={dialog||undefined} onClose={()=>setDialog(false)}/>}</div>}
